services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-usersdb}
      MYSQL_USER: ${MYSQL_USER:-app_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app_password}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$MYSQL_USER -p$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - dbdata:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: UserApi/Dockerfile 
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: "Server=db;Port=3306;Database=${MYSQL_DATABASE:-usersdb};Uid=${MYSQL_USER:-app_user};Pwd=${MYSQL_PASSWORD:-app_password};AllowPublicKeyRetrieval=True;SslMode=None;TreatTinyAsBoolean=true;"
    ports:
      - "${API_PORT:-5000}:8080"
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  dbdata:
